org: andresafag
app: my-app
service: express-pug-app

frameworkVersion: '4'
custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1 
  stage: dev
  environment:
    API_KEY: ${env:API_KEY}

    # OTel — self-managed SDK, no ADOT layer needed
    # Full signal-specific path required for Prometheus OTLP ingestion
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://44.210.111.254:9090/api/v1/otlp/v1/metrics"
    OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
    OTEL_METRICS_EXPORTER: "otlp"
    OTEL_METRIC_EXPORT_INTERVAL: "5000"
    OTEL_METRIC_EXPORT_TIMEOUT: "3000"
    OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "CUMULATIVE"
    OTEL_SERVICE_NAME: "foodmania-api"

  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any


package:
  individually: true
  patterns:
    - '!**'                
    - '../app.js'
    - '../handler.js'
    - '../package.json'
    - '../node_modules/**'
    - '../views/**'        
    - '../public/**'       
